os: linux
arch:
  - amd64
  - arm64
dist: bionic
language: python
cache: pip
group: travis_latest

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - PIP=Red-DiscordBot
  - PIP="-r https://github.com/HelloZeroNet/ZeroNet/raw/py3/requirements.txt"

install:
  - sudo apt update -q
  - sudo apt install -qy python3-dev python3-wheel
  - pip3 install twine

script:
  - make

jobs:
  exclude:
    - python: "3.6"
      env: PIP=Zeronet
