FROM {% if arch is defined %}{{arch}}/python:3-buster{% else %}python:3-buster{% endif %}

RUN apt-get update -q \
  # && apt-get install --no-install-recommends -qy build-essential python3-dev python3-pip python3-setuptools python3-wheel \
  && pip3 install twine wheel \
  && rm -rf /var/lib/apt/lists/*

COPY [ "Makefile", "/data/" ]

VOLUME /data/packages
WORKDIR /data
CMD [ "make" ]
