---
version: "2.4"

services:
  pypi-builder:
    extends:
      file: $HOME/docker-compose-files/common.yml
      service: common
    build:
      context: .
      dockerfile: Dockerfile
    image: supersandro2000/pypi-builder
    cap_drop:
      - ALL
    cap_add:
      - chown
      - dac_override
      - fowner
      - setgid
      - setuid
    volumes:
      - $PWD/packages:/packages
    env_file: secrets.env
