{% if DIST is not defined or DIST == "buster" %}
FROM {% if ARCH is defined %}{{ARCH}}/{% endif %}python:{% if PY_VERSION is defined %}{{PY_VERSION}}{% else %}3{% endif %}-buster
{% endif %}

{%- if DIST == "alpine" %}
FROM {% if ARCH is defined %}{{ARCH}}/{% endif %}alpine:{{ALPINE_VERSION}}
{% endif %}


{% if DIST == "buster" %}
RUN apt update \
  && apt install -y twine
{% endif %}

{%- if DIST == "alpine" %}
# for scripts and very common, not to big build dependencies.
RUN apk add --no-progress bash g++ git make python3-dev py3-pip py3-wheel py3-twine

RUN pip3 install --upgrade pip

# ordered by popularity to try cache things

{%- if "cryptography" or "gevent" in PIP %}
RUN apk add --no-progress libffi-dev
{%- endif %}

{%- if "cryptography" in PIP %}
RUN apk add --no-progress cargo openssl-dev rust
{%- endif %}

{%- if "Kibitzr" or "lxml" in PIP %}
RUN apk add --no-progress libxml2-dev libxslt-dev
{%- endif %}

{%- if "coincurve" in PIP %}
RUN apk add --no-progress autoconf automake libtool
{%- endif %}

{%- if "psycopg2-binary" in PIP %}
RUN apk add --no-progress postgresql-dev
{%- endif %}

{%- if "healthchecks" in PIP %}
RUN apk add --no-progress postgresql-dev
{%- endif %}

{%- endif %}

COPY [ "Makefile", "/data/" ]

VOLUME /data/packages
WORKDIR /data
CMD [ "make" ]
